### PR TITLE
SDK Python Interface for inferenceable columns API Endpoint

### PR DESCRIPTION
**Pull request by ryttry**
This PR creates a Python interface over the "inferenceable columns" API endpoint. Specifically, users can make columns non-inferenceable by passing in a list of undesired column names to function `ignore_col_flag`, or make columns inferenceable by passing in a list of desired column names to function `set_col_flag`.

Since the "inferenceable columns" API endpoint requires an exhaustive list of the dataset columns' inferenceability, column names of the dataset that are not passed into the Python interface are naturally deemed to be the opposite of the column names that are passed in. For example, for a dataset with columns ["A", "B", "C"],
- if the user ignores columns ["A", "C"], then ["B"] would be activated (inferenceable).
- if the user activates columns ["C", "B"], then ["A"] would be ignored (non-inferenceable).

By virtue of the API endpoint being rudimentary, validation of the abstracted friendly interface is done in the Python code. For example, if the user ignores columns ["C", "A", "Z"] for a dataset with columns ["A", "B", "C"], then an informative message will be returned to the user and the "inferenceable columns" API endpoint will not be invoked (See code for more validation paths). In the above case, column "Z" is non-existent in the dataset.

Discussion: While the above improves over the direct use of the raw API endpoint, going forward it would be even more user-friendly to be able to _change the flag of specified columns, while keeping the un-mentioned columns unchanged_. To enable this, another API endpoint that returns the current inferenceability state of all columns is required. 

Generally, this discussion should apply to all properties of columns, of which inferenceability is one.

### CODE REVIEW

**Comment by ryttry** [comment]
[sc-9692]

**Comment by davidstanley01** [comment]
@ryttry Is it worth putting the column inference status on the project summary rather than adding a new endpoint?

**Review by davidstanley01 — APPROVED** [review]

**Comment by ryttry** [comment]
@davidstanley01, I think your suggestion makes good sense. Further, when we have more and more column properties, we'll see it as an increasing part of the project state in the summary. As an aside, at this point, I'm just wondering if everything about the watchful client and current project should be retrievable via summary or if there should be some separation.

**Comment by inimino** [comment]
The frontend will want to know about the inferencable columns, so adding them to the summary would make sense.

**Comment by inimino** [comment]
@ryttry I can describe the desiderata of our current architecture:

Principle: If information is presented in the frontend, it should be always be in the summary.

For API users, this means you can explore everything there is with just generic tools `curl | jq`.

Q: What about the size of the requests? Wouldn't it be more efficient to have hundreds of requests to individual endpoints like a typical web app so that information isn't being duplicated?

A: The information presented in the frontend is also always "human scale" information. It's something a human can look at and take in as a single screenful of information. This implies that if we have a chart that summarizes the entire dataset, we generate the chart on the backend rather than sending an unbounded amount of data to the frontend and generating a chart there, but that's what we'd want to do anyway. One place where we currently break this design criteria is the candidates, where we simply always send 8 full rows, regardless of the weight in bytes. The frontend does its own truncation of these and adds "see more", which shows that the data is not human scale according to our definition. If we were to summarize the rows on the backend, this would improve performance and improve the internal consistency of our design. Given "human scale" summaries, the network latency will never jeopardize our performance guarantees.

Q: What if it eventually becomes too much anyway? If we keep adding features to the product and every feature adds something to the summary, won't this eventually jeopardize our performance guarantees and degrade the user experience?

A: Yes! And then we solve the whole problem instantly in a generic way that requires no new frontend or backend code, but a small component on both sides of the interface, which takes the form of two functions:

diff(json_object, json_object) -> json_patch_object
patch(json_object, json_patch_object) -> json_object

These functions are perfectly generic, not specific to any of our data types at all, only requiring JSON. We transparently plug in a component to the frontend that instead of saying "give me the summary" says "I have the summary version 1832, give me the diff from that", and the backend says either "I still have 1832 in memory, here is the diff" or "I don't, here is the complete summary again" and then the component then applies the diff, and returns the summary object. Nothing downstream of this needs to know about this network-layer optimization. Incidentally we already have a `state_seq` value defined, which is incremented every time the state of the project changes in a way that is observable via the summary, in other words there is a deterministic mapping from `state_seq` to a specific summary object. The groundwork is already there for a diff-patch mechanism as we already have the versioning system in place that this mechanism requires.

Anyway, I am sharing all this as it is both part of the current architecture and part of the architectural thinking that informed how we would address these issues in the future, for example, the deterministic nature of `state_seq` did not happen by accident, but arises from the conceptual integrity of the architecture, including the future plans. As architectural decisions will be distributed across the entire org rather than made just once, to the extent that the architectural perspective can be shared, the conceptual integrity of the design can be maintained, otherwise it will gradually drift according to different persons' understandings.

**Comment by davidstanley01** [comment]
I added a [shortcut story](https://app.shortcut.com/watchful/story/9780/show-inferenced-columns-in-the-project-summary) to capture the "add inferenced columns to project summary" idea. We'll discuss it as part of the Inference Columns UI story-mapping exercise.

**Pull request merged**
